# Generated by Django 6.0.1 on 2026-01-28 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_tripplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLogbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('index', models.PositiveIntegerField(default=1)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbooks', to='trips.tripplan')),
            ],
            options={
                'ordering': ['trip_plan', 'date', 'index'],
                'unique_together': {('trip_plan', 'date', 'index')},
            },
        ),
    ]
